### ISSUE TITLE
Iterating over processes/netconns throws "object mutated"

### ISSUE THREAD

**Issue by adamsmutnicki** [carbonblack/cbapi-python#53]
Hi,
This is similar case as #40. We have tried using lru.py from #40, but without success. It throws object mutated again. Below is the trace. Is there other, even unreleased version of lru.py for testing?
Adam

Traceback (most recent call last):
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 265, in __call__
   return self.cache[key]
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 44, in withlock
   return func(self, *args, **kwargs)
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 175, in __getitem__
   del self.__access_times[key]
KeyError: '((<cbapi.response.rest_api.CbResponseAPI object at 0x7fb2c93c0ef0>, <class \'cbapi.response.models.Process\'>, \'00000017-0000-1140-01d2-45e54d6f3f40\', 1), {\'initial_data\': {\'modload_count\': 14, \'emet_count\': 0, \'segment_id\': 1, \'process_md5\': \'e21493887e77353fd489699848ec84f0\', \'comms_ip\': -1738898902, \'start\': \'2016-11-23T23:57:09.612Z\', \'id\': \'00000017-0000-1140-01d2-45e54d6f3f40\', \'interface_ip\': -1738898902, \'terminated\': True, \'process_pid\': 4416, \'parent_pid\': 352, \'cmdline\': \'\\\\??\\\\C:\\\\Windows\\\\system32\\\\conhost.exe "90634112817277488881085487060191274526151857280415523981982108754250-1966886061"\', \'filemod_count\': 0, \'childproc_count\': 0, \'sensor_id\': 23, \'hostname\': \'WAVE2-01\', \'netconn_count\': 0, \'process_name\': \'conhost.exe\', \'path\': \'c:\\\\windows\\\\system32\\\\conhost.exe\', \'username\': \'SYSTEM\', \'crossproc_count\': 4, \'os_type\': \'windows\', \'current_segment\': 0, \'unique_id\': \'00000017-0000-1140-01d2-45e54d6f3f40-00000001\', \'host_type\': \'server\', \'regmod_count\': 0, \'group\': \'Default Group\', \'parent_unique_id\': \'00000017-0000-0160-01d2-452a9f897f3a-00000001\', \'last_update\': \'2016-11-23T23:57:09.839Z\', \'parent_md5\': \'000000000000000000000000000000\', \'processblock_count\': 0, \'emet_config\': \'\', \'parent_name\': \'csrss.exe\'}})#select_instance'During handling of the above exception, another exception occurred:Traceback (most recent call last):

 File "./cb_from_server_feed_netconns.py", line 93, in <module>
   sys.exit(main())
 File "./cb_from_server_feed_netconns.py", line 82, in main
   for process in c.select(Process):
 File "/usr/lib/python3.5/site-packages/cbapi/query.py", line 211, in _perform_query
   yield self._doc_class.new_object(self._cb, item)
 File "/usr/lib/python3.5/site-packages/cbapi/response/models.py", line 1632, in new_object
   return cb.select(Process, item['id'], long(item['segment_id']), initial_data=item)
 File "/usr/lib/python3.5/site-packages/cbapi/connection.py", line 243, in select
   return select_instance(self, cls, unique_id, *args, **kwargs)
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 268, in __call__
   self.cache[key] = value
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 44, in withlock
   return func(self, *args, **kwargs)
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 170, in __setitem__
   self.cleanup()
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 44, in withlock
   return func(self, *args, **kwargs)
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 211, in cleanup
   marked_for_deletion = [k for k in islice(self.__access_times, number_to_delete)]
 File "/usr/lib/python3.5/site-packages/cbapi/cache/lru.py", line 211, in <listcomp>
   marked_for_deletion = [k for k in islice(self.__access_times, number_to_delete)]
RuntimeError: OrderedDict mutated during iteration

**Comment by jgarman** [comment]
This is fixed in upcoming 1.0.1 release
