### ISSUE TITLE
Iterating over processes throws an error in lru in Python 2.7

### ISSUE THREAD

**Issue by adamsmutnicki** [carbonblack/cbapi-python#54]
While iterating over Processes, we again have problem with obj. mutated in python 3.5. So we moved to Python 2.7. We ended up with different error from lru liblary:

Traceback (most recent call last):
 File "./cb_from_server_feed_netconns.py", line 93, in <module>
   sys.exit(main())
 File "./cb_from_server_feed_netconns.py", line 82, in main
   for process in c.select(Process):
 File "/usr/lib/python2.7/site-packages/cbapi/query.py", line 211, in _perform_query
   yield self._doc_class.new_object(self._cb, item)
 File "/usr/lib/python2.7/site-packages/cbapi/response/models.py", line 1632, in new_object
   return cb.select(Process, item['id'], long(item['segment_id']), initial_data=item)
 File "/usr/lib/python2.7/site-packages/cbapi/connection.py", line 243, in select
   return select_instance(self, cls, unique_id, *args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 269, in __call__
   self.cache[key] = value
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 44, in withlock
   return func(self, *args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 170, in __setitem__
   self.cleanup()
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 44, in withlock
   return func(self, *args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 214, in cleanup
   self.__delete__(k)
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 44, in withlock
   return func(self, *args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cbapi/cache/lru.py", line 183, in __delete__
   del self.__values[key]
KeyError: '((<cbapi.response.rest_api.CbResponseAPI object at 0x7fa741450790>, <class \'cbapi.response.models.Process\'>, u\'00000014-0000-1e24-01d2-45e242d34916\', 1L), {\'initial_data\': {u\'process_md5\': u\'c68a9321b783be9641c6a51c68c01004\', u\'sensor_id\': 20, u\'modload_count\': 45, u\'parent_unique_id\': u\'00000014-0000-1d50-01d2-45e242cc1cc4-00000001\', u\'cmdline\': u\'tasklist /FI "imagename eq perl*" /SVC /FO CSV\', u\'last_update\': u\'2016-11-23T23:35:23.374Z\', u\'id\': u\'00000014-0000-1e24-01d2-45e242d34916\', u\'parent_name\': u\'perl514.exe\', u\'parent_md5\': u\'000000000000000000000000000000\', u\'group\': u\'Default Group\', u\'comms_ip\': -1062703507, u\'hostname\': u\'WORKSPACE\', u\'filemod_count\': 0, u\'start\': u\'2016-11-23T23:35:23.323Z\', u\'emet_config\': u\'\', u\'regmod_count\': 0, u\'interface_ip\': -1062703507, u\'process_pid\': 7716, u\'username\': u\'SYSTEM\', u\'terminated\': True, u\'process_name\': u\'tasklist.exe\', u\'emet_count\': 0, u\'path\': u\'c:\\\\windows\\\\syswow64\\\\tasklist.exe\', u\'netconn_count\': 0, u\'parent_pid\': 7504, u\'crossproc_count\': 1, u\'current_segment\': 0, u\'segment_id\': 1, u\'host_type\': u\'server\', u\'processblock_count\': 0, u\'os_type\': u\'windows\', u\'childproc_count\': 0, u\'unique_id\': u\'00000014-0000-1e24-01d2-45e242d34916-00000001\'}})#select_instance'

**Comment by jgarman** [comment]
This is fixed in upcoming 1.0.1
