### ISSUE TITLE
ImportError: cannot import name python_2_unicode_compatible

### ISSUE THREAD

**Issue by mbabatunde** [carbonblack/cbapi-python#72]
Hi!

I'm currently trying to get started using Carbon Black's API and after doing the pip install cbapi, I've been having issues authenticating my token. I have all the modules installed that were listed under the required.txt file. Currently using Python 2.7.10 (but also tried this with Python 3.6.1) and I'm receiving this issue when starting the initial credential file:

`cbapi-response configure`

Error after running that line:

```File "/usr/local/bin/cbapi-response", line 3, in <module>
  from cbapi.response.cli import main
File "/Library/Python/2.7/site-packages/cbapi/__init__.py", line 15, in <module>
   from .response.rest_api import CbEnterpriseResponseAPI, CbResponseAPI
File "/Library/Python/2.7/site-packages/cbapi/response/__init__.py", line 5, in <module>
   from .models import (
File "/Library/Python/2.7/site-packages/cbapi/response/models.py", line 22, in <module>
   from ..oldmodels import BaseModel, MutableModel, immutable
File "/Library/Python/2.7/site-packages/cbapi/oldmodels.py", line 9, in <module>
   from six import python_2_unicode_compatible, iteritems
ImportError: cannot import name python_2_unicode_compatible
```
I was also suggested to upgrade the six module, but that has proven to be unsuccessful with this error:

```
Collecting six
 Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
Found existing installation: six 1.4.1
   DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
       Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
   status = self.run(options, args)
 File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in
 run
   prefix=options.prefix_path,
 File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
   requirement.uninstall(auto_confirm=True)
 File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
   paths_to_remove.remove(auto_confirm)
 File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
   renames(path, new_path)
 File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
   shutil.move(old, new)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
   copy2(src, real_dst)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
   copystat(src, dst)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
   os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: 
'/var/folders/3v/98px7zzx7_57tmwbxk_1wddhgd52vm/T/pip-GS0e5n-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```
Any suggestions on what I can do to get the REST API Python binding to work?

**Comment by mbabatunde** [comment]
After doing a clean install of Python 3.6.1 again, everything started working and I was successfully authenticated
