### ISSUE TITLE
Fix unicode support for Windows console once and for all

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cbapi-python#85]
Use the same package ipython does: [win-unicode-console](https://github.com/Drekin/win-unicode-console)

**Comment by 0duck0** [comment]
Is the following issue that I had, related to this?

I tried to run the watchlist_exporter.py from a Windows Anaconda2 prompt.  My error output:
Traceback (most recent call last):
  File "\\gold.rtgold.nima.mil\home\nde_users_37\duckwots\Profile\Desktop\watchl
ist_exporter.py", line 91, in <module>
    sys.exit(main())
  File "\\gold.rtgold.nima.mil\home\nde_users_37\duckwots\Profile\Desktop\watchl
ist_exporter.py", line 87, in main
    return export_watchlists(cb, args)
  File "\\gold.rtgold.nima.mil\home\nde_users_37\duckwots\Profile\Desktop\watchl
ist_exporter.py", line 59, in export_watchlists
    "SearchString": watchlist.query,
  File "C:\Anaconda2\lib\site-packages\cbapi\response\models.py", line 1049, in
query
    queryparts.append("{0}:{1}".format(k[5:], v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-16: ord
inal not in range(128)

**Comment by 0duck0** [comment]
Is my issue related?  
I was unable to get the desired output from the watchlist_output.py

Traceback (most recent call last):
  File "watchlist_exporter.py", line 91, in <module>
    sys.exit(main())
  File "watchlist_exporter.py", line 87, in main
    return export_watchlists(cb, args)
  File "watchlist_exporter.py", line 59, in export_watchlists
    "SearchString": watchlist.query,
  File "C:\Anaconda2\lib\site-packages\cbapi\response\models.py", line 1049, in query
    queryparts.append("{0}:{1}".format(k[5:], v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-16: ordinal not in range(128)

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
