### ISSUE TITLE
Sensor flush_events returns 500 on Cb Response 6.1.X

### ISSUE THREAD

**Issue by askthedragon** [carbonblack/cbapi-python#90]
Here is the exception:

`2017-10-12 22:50:01 [26502] <err>  cb.flask.blueprint_helpers - Unhandled exception from API request: time data '2017-10-13 22:50:01.420281' does not match format '%a, %d %b %Y %H:%M:%S %Z'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/jenkins/build/workspace/build-cbent-signed-docker-6.1.2-respin/code/coreservices/src/cb/auth/auth.py", line 107, in wrapped_f
  File "/usr/lib/python2.6/site-packages/cb/flask/blueprints/api_blueprint.py", line 1191, in host_wrapper_v1
  File "/usr/lib/python2.6/site-packages/cb/flask/blueprints/api_blueprint.py", line 1298, in _hosts
  File "/opt/jenkins/build/workspace/build-cbent-signed-docker-6.1.2-respin/code/coreservices/src/cb/api/api_engine.py", line 490, in hosts_update
  File "/usr/lib64/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017-10-13 22:50:01.420281' does not match format '%a, %d %b %Y %H:%M:%S %Z'`

**Comment by jgarman** [comment]
fixed in 4339e7fd8cce623b9a1ba286237692d750130cff
